{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cascade",
    "module": "pci-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "pci-sdk-1.0.4.aar",
          "url": "pci-sdk-1.0.4.aar",
          "size": 637394,
          "sha512": "3bfb2cb633d066ec8b118d5c5316214434f7baac8e75b1a108761a94bd67c8380614214c4e85a542b1e19b3c2aa4086a402ba5e01d5b14c7c4e6d35a67727a30",
          "sha256": "91e89c83e35a23a395197425f1e2dae93fca9ef4675a24191b3b44ef382f98cd",
          "sha1": "2886a22f66160dab697d349f06a03a608218e9fa",
          "md5": "f195521045f4d676d4c0cf43acbadd7f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-placeholder-material",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "pci-sdk-1.0.4.aar",
          "url": "pci-sdk-1.0.4.aar",
          "size": 637394,
          "sha512": "3bfb2cb633d066ec8b118d5c5316214434f7baac8e75b1a108761a94bd67c8380614214c4e85a542b1e19b3c2aa4086a402ba5e01d5b14c7c4e6d35a67727a30",
          "sha256": "91e89c83e35a23a395197425f1e2dae93fca9ef4675a24191b3b44ef382f98cd",
          "sha1": "2886a22f66160dab697d349f06a03a608218e9fa",
          "md5": "f195521045f4d676d4c0cf43acbadd7f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pci-sdk-1.0.4-sources.jar",
          "url": "pci-sdk-1.0.4-sources.jar",
          "size": 161335,
          "sha512": "144d103342ccf28ac681a59b03f940e72924af6bd35f5e7f35785117ae3e3a23f5808b091995dfaa66b203f991dda18ddcbe0bed7d3efc9f10585590d5eb41fe",
          "sha256": "f791eb08eec51fc7803ceeb0b188770de3aebe7ac41f5c9aeaaef534e2b22ace",
          "sha1": "89a346da05fa01935d26e2c3607becb9e771ba74",
          "md5": "88cd94a37e6b38a1bc3793d308ee72a5"
        }
      ]
    }
  ]
}
