{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cascade",
    "module": "pci-sdk",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "pci-sdk-1.0.6.aar",
          "url": "pci-sdk-1.0.6.aar",
          "size": 638163,
          "sha512": "94608d2e9e2ac44e6b53a3d811e967cb9fed0706165abcd42f5bfa3ef546b9269e43b43ac7918f64854801048c248cc68ea3c29bc9f3b7153a6d6f9107699492",
          "sha256": "507b96a983518800e83e0923f11feeac755b4bdf219eec8b28d0fbecedca8289",
          "sha1": "18a5d5be4985b855efac64911a1f7ad9753d2a18",
          "md5": "77507b043f7dfaf2a61e6411c360c8d8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-placeholder-material",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "pci-sdk-1.0.6.aar",
          "url": "pci-sdk-1.0.6.aar",
          "size": 638163,
          "sha512": "94608d2e9e2ac44e6b53a3d811e967cb9fed0706165abcd42f5bfa3ef546b9269e43b43ac7918f64854801048c248cc68ea3c29bc9f3b7153a6d6f9107699492",
          "sha256": "507b96a983518800e83e0923f11feeac755b4bdf219eec8b28d0fbecedca8289",
          "sha1": "18a5d5be4985b855efac64911a1f7ad9753d2a18",
          "md5": "77507b043f7dfaf2a61e6411c360c8d8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pci-sdk-1.0.6-sources.jar",
          "url": "pci-sdk-1.0.6-sources.jar",
          "size": 160625,
          "sha512": "4183ee3a1548aa6b4f335b2bd8085ebf00f4bb6e98c99f8faec0518514ffeb0134d99f5b131d78cff01ed12b250658c0bed647b71d6908fe0cab39bfd85c05ed",
          "sha256": "a19c519d03916763f63a08f6be50a4d2dc9a3470f2459a3851ac80670d5c00c5",
          "sha1": "24a9539525167f80523e98487a37442d51fd8f33",
          "md5": "d35f4f678df34d53be1a275cf730281a"
        }
      ]
    }
  ]
}
