{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cascade",
    "module": "pci-sdk",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "pci-sdk-1.0.5.aar",
          "url": "pci-sdk-1.0.5.aar",
          "size": 637678,
          "sha512": "3cec70504bf4a45cf1add9505330afed67b7a3b5d24837d8ae60486e132c0c2d252e0ca87ccc082cec511fa840d681483bf823c8ee881d03eb6acc93b91b2777",
          "sha256": "41d85b8131cdc0fe36ebdc5df3fbc7f86475833660995db84988b1ccd20c3b95",
          "sha1": "c1be4e946a22eb9fff3b16c07f516b7acee17d05",
          "md5": "ba030c0db61bde0e0eb83190bbc11797"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-placeholder-material",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "pci-sdk-1.0.5.aar",
          "url": "pci-sdk-1.0.5.aar",
          "size": 637678,
          "sha512": "3cec70504bf4a45cf1add9505330afed67b7a3b5d24837d8ae60486e132c0c2d252e0ca87ccc082cec511fa840d681483bf823c8ee881d03eb6acc93b91b2777",
          "sha256": "41d85b8131cdc0fe36ebdc5df3fbc7f86475833660995db84988b1ccd20c3b95",
          "sha1": "c1be4e946a22eb9fff3b16c07f516b7acee17d05",
          "md5": "ba030c0db61bde0e0eb83190bbc11797"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pci-sdk-1.0.5-sources.jar",
          "url": "pci-sdk-1.0.5-sources.jar",
          "size": 161347,
          "sha512": "87636f06f27fe96a3bb4cb15a277287f280da84750113bad9532091065793a528607733aaa78f157f389ab2b8b8dbab351beccee2ee854ab799e69b560cb957b",
          "sha256": "4634961f9d4548ec0e74833bc933841045531cfcc0641cd731c9ff7aee4c1e54",
          "sha1": "32bfbfca284c601ea0e595baf5b76121f8aed9bb",
          "md5": "b0f3dc365dfccdaef6373dc01cc04bfc"
        }
      ]
    }
  ]
}
